# Generated by Django 2.0.5 on 2018-05-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedapi',
            name='url',
            field=models.URLField(default='URL', unique=True, verbose_name='URL'),
        ),
    ]
