# Generated by Django 2.0.5 on 2018-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed_api', '0002_pubmedapi_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmedapi',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='pubmedapi',
            name='url',
            field=models.CharField(max_length=30, unique=True, verbose_name='URL'),
        ),
    ]
