# Generated by Django 2.0.5 on 2018-05-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed_api', '0003_auto_20180531_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmedapi',
            name='url',
            field=models.CharField(max_length=30, verbose_name='URL'),
        ),
    ]
