# Generated by Django 2.0.5 on 2018-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed_api', '0007_auto_20180531_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubmedapi',
            name='content',
        ),
        migrations.AlterField(
            model_name='pubmedapi',
            name='description',
            field=models.TextField(verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='pubmedapi',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='pubmedapi',
            name='url',
            field=models.CharField(max_length=20, null=True, verbose_name='URL'),
        ),
    ]
